services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - .:/app                  # Mount entire project
      - /app/node_modules       # Anonymous volume for node_modules
    ports:
      - '${APP_PORT_EXTERNAL:-3002}:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DATABASE_URL=${DATABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    # Automatically install dependencies on every startup
    command: sh -c "pnpm install && pnpm run start:dev"

  postgres:
    image: postgres:17
    ports:
      - '${DB_PORT_EXTERNAL:-5433}:5432'
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USER} -d ${DB_NAME}']
      interval: 1s
      timeout: 3s
      retries: 5

  redis:
    image: redis:8
    ports:
      - '${REDIS_PORT_EXTERNAL:-6379}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5

volumes:
  postgres_data:
  redis_data:
