services:
  postgres-test:
    image: postgres:17
    environment:
      - POSTGRES_USER=${TEST_DB_USER}
      - POSTGRES_PASSWORD=${TEST_DB_PASSWORD}
      - POSTGRES_DB=${TEST_DB_NAME}
    ports:
      - '${TEST_DB_PORT_EXTERNAL:-5434}:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${TEST_DB_USER} -d ${TEST_DB_NAME}']
      interval: 1s
      timeout: 3s
      retries: 20

  redis-test:
    image: redis:8
    ports:
      - '${TEST_REDIS_PORT_EXTERNAL:-6380}:6379'
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 5
