services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '${APP_PORT_EXTERNAL:-3002}:3000'
    depends_on:
      - postgres
      - redis
    environment:
      - DATABASE_URL=postgresql://${DB_USERNAME}:${DB_PASSWORD}@postgres:5432/${DB_NAME}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}

  postgres:
    image: postgres:17
    ports:
      - '${POSTGRES_PORT_EXTERNAL:-5433}:5432'
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 1s
      timeout: 3s
      retries: 20

  redis:
    image: redis:8
    ports:
      - '${REDIS_PORT_EXTERNAL:-6379}:6379'
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  postgres_data:
  redis_data:
